#! /usr/bin/env bash
#
# Runs the Mocha tests using Headless Chrome

cd "${BASH_SOURCE[0]%/*}"
SCRIPTS_DIR="$PWD"
ROOT_DIR="${SCRIPTS_DIR%/*}"

test_with_headless_chrome() {
  local port=8080
  local server_pid
  local result

  set -m
  "$SCRIPTS_DIR/test-server.js" "$port" &

  if [[ "$?" -ne 0 ]]; then
    printf "Failed to launch test server on port $port\n" >&2
    return 1
  elif [[ -n "$CI" ]]; then
    sleep 3
  fi
  server_pid="$!"

  "$ROOT_DIR/node_modules/.bin/mocha-chrome" --reporter spec \
    http://localhost:8080/test/
  result="$?"
  kill -INT "$server_pid"
  set +m
  return "$result"
}

test_with_headless_chrome
